# Generated by Django 4.1.4 on 2023-02-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_productdeme_alter_post_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='cover/'),
        ),
    ]
