# Generated by Django 4.1.4 on 2023-04-04 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_books'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
